"""Add insights_reports table for AI conversation insights

Revision ID: 032_add_insights_reports
Revises: 031_add_request_count
Create Date: 2026-04-16

This migration adds a table for storing AI conversation insights reports.
Each report contains a user's conversation analysis results generated by
the AI model, including scores, strengths, areas for improvement, and
actionable suggestions.

"""

from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "032_add_insights_reports"
down_revision: Union[str, None] = "031_add_request_count"
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def _table_exists(conn, table_name: str) -> bool:
    """Check if a table exists."""
    if conn.dialect.name == "postgresql":
        result = conn.execute(
            sa.text("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables
                    WHERE table_schema = 'public' AND table_name = :table_name
                )
                """),
            {"table_name": table_name},
        )
        return result.fetchone()[0]
    else:
        result = conn.execute(
            sa.text("SELECT name FROM sqlite_master WHERE type='table' AND name = :table_name"),
            {"table_name": table_name},
        )
        return result.fetchone() is not None


def _index_exists(conn, table_name: str, index_name: str) -> bool:
    """Check if an index exists."""
    if conn.dialect.name == "postgresql":
        result = conn.execute(
            sa.text("SELECT 1 FROM pg_indexes WHERE indexname = :index_name"),
            {"index_name": index_name},
        )
    else:
        result = conn.execute(
            sa.text("SELECT 1 FROM sqlite_master WHERE type='index' AND name = :index_name"),
            {"index_name": index_name},
        )
    return result.fetchone() is not None


def upgrade() -> None:
    """Add insights_reports table."""
    conn = op.get_bind()
    is_postgresql = conn.dialect.name == "postgresql"

    if not _table_exists(conn, "insights_reports"):
        if is_postgresql:
            op.execute(sa.text("""
                    CREATE TABLE insights_reports (
                        id SERIAL PRIMARY KEY,
                        user_id INTEGER NOT NULL REFERENCES users(id),
                        start_date VARCHAR(10) NOT NULL,
                        end_date VARCHAR(10) NOT NULL,
                        overall_score INTEGER,
                        overall_assessment TEXT,
                        strengths TEXT,
                        areas_for_improvement TEXT,
                        suggestions TEXT,
                        usage_summary TEXT,
                        model VARCHAR(50),
                        raw_response TEXT,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """))
        else:
            op.execute(sa.text("""
                    CREATE TABLE insights_reports (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        user_id INTEGER NOT NULL,
                        start_date VARCHAR(10) NOT NULL,
                        end_date VARCHAR(10) NOT NULL,
                        overall_score INTEGER,
                        overall_assessment TEXT,
                        strengths TEXT,
                        areas_for_improvement TEXT,
                        suggestions TEXT,
                        usage_summary TEXT,
                        model VARCHAR(50),
                        raw_response TEXT,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """))

    if not _index_exists(conn, "insights_reports", "idx_insights_reports_user_date"):
        op.execute(
            sa.text(
                "CREATE INDEX idx_insights_reports_user_date ON insights_reports(user_id, start_date, end_date)"
            )
        )


def downgrade() -> None:
    """Remove insights_reports table."""
    conn = op.get_bind()

    if _index_exists(conn, "insights_reports", "idx_insights_reports_user_date"):
        op.execute(sa.text("DROP INDEX IF EXISTS idx_insights_reports_user_date"))

    if _table_exists(conn, "insights_reports"):
        op.execute(sa.text("DROP TABLE insights_reports"))
