#!/bin/bash
# generate-sudoers.sh - Unified sudoers generator for Issue #2334
#
# Single source of truth for sudoers configuration used by both Docker and Package.
# All conditionals are resolved BEFORE writing to the sudoers file.
#
# Usage: generate-sudoers.sh --output <file> [--user <user>] [--dry-run]
#
# Exit codes:
#   0 - Success
#   1 - Invalid arguments
#   2 - Required wrapper missing
#   3 - visudo validation failed
#   4 - Write failed

set -euo pipefail

# Default values
OUTPUT_FILE=""
RUN_USER="open-ace"
DRY_RUN=false
INSTALL_DIR=""

# Audit log configuration
AUDIT_LOG="${AUDIT_LOG:-/var/log/openace/sudoers-audit.log}"

usage() {
    echo "Usage: $0 --output <file> [--user <user>] [--install-dir <dir>] [--dry-run]"
    echo ""
    echo "Options:"
    echo "  --output <file>      Output sudoers file path (required)"
    echo "  --user <user>        Service user (default: open-ace)"
    echo "  --install-dir <dir>  Installation directory for path resolution"
    echo "  --dry-run            Show generated content without writing"
    exit 1
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        --user)
            RUN_USER="$2"
            shift 2
            ;;
        --install-dir)
            INSTALL_DIR="$2"
            shift 2
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        -h|--help)
            usage
            ;;
        *)
            echo "Unknown option: $1" >&2
            usage
            ;;
    esac
done

if [[ -z "$OUTPUT_FILE" ]]; then
    echo "ERROR: --output is required" >&2
    usage
fi

# ============================================================================
# Resolve all paths and validate wrappers BEFORE generating content
# ============================================================================

# Resolve git and gh paths
GIT_PATH=$(which git 2>/dev/null || echo "/usr/bin/git")
GH_PATH=$(which gh 2>/dev/null || echo "/usr/bin/gh")

# Resolve WebUI path
WEBUI_PATH=$(which qwen-code-webui 2>/dev/null || echo "/usr/bin/qwen-code-webui")

# Validate required wrappers exist and are executable (skip in dry-run mode)
# In dry-run mode, we're testing the output format, not actual installation
WEBUI_LAUNCH_WRAPPER="/usr/local/bin/openace-webui-launch"
RUN_AS_WRAPPER="/usr/local/bin/openace-run-as"

if [[ "$DRY_RUN" != true ]]; then
    if [[ ! -x "$WEBUI_LAUNCH_WRAPPER" ]]; then
        echo "ERROR: Required wrapper not executable: $WEBUI_LAUNCH_WRAPPER" >&2
        echo "       WebUI launcher wrapper must be installed before generating sudoers" >&2
        exit 2
    fi

    if [[ ! -x "$RUN_AS_WRAPPER" ]]; then
        echo "ERROR: Required wrapper not executable: $RUN_AS_WRAPPER" >&2
        exit 2
    fi
fi

# ============================================================================
# Build sudoers content with all conditionals pre-resolved
# ============================================================================

# Build WebUI launcher rules (fail-closed, no fallback)
WEBUI_RULES="${RUN_USER} ALL=(ALL) NOPASSWD: ${WEBUI_LAUNCH_WRAPPER} * \"${WEBUI_PATH}\" *"

# Build run-as wrapper rules
WRAPPER_RULE="${RUN_USER} ALL=(root) NOPASSWD: ${RUN_AS_WRAPPER} --isolated *"

# Build security wrapper rules
# In dry-run mode, show all expected wrappers for testing
# In production mode, only include wrappers that actually exist
SECURITY_WRAPPERS_RULES=""
for wrapper in openace-chown openace-useradd openace-cat openace-mkdir openace-write-as openace-rm; do
    wrapper_path="/usr/local/bin/${wrapper}"
    if [[ "$DRY_RUN" = true ]] || [[ -x "$wrapper_path" ]]; then
        SECURITY_WRAPPERS_RULES="${SECURITY_WRAPPERS_RULES}
${RUN_USER} ALL=(root) NOPASSWD: ${wrapper_path} *"
    fi
done

# Build GH admin rule (opt-in only)
GH_ADMIN_RULE=""
if [[ "${OPENACE_ALLOW_ADMIN_MERGE:-}" = "1" ]]; then
    GH_ADMIN_RULE="${GH_PATH} pr merge * --admin, \\
    "
fi

# Generate the sudoers content
# Key change for Issue #2334: GIT_SAFE and GH_SAFE use (ALL) runas
# to allow github_ops to run as system_account
SUDOERS_CONTENT="# Open ACE WebUI - Multi-user workspace sudo configuration
# Auto-generated by generate-sudoers.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Issue #2334: Unified generator for Docker and Package paths
#
# Support both open-ace (container user) and openace (workspace user synced from database)

# ============================================================================
# 【安全加固 Issue #2334】精确参数白名单配置
# ============================================================================
# 基于sudoers审计报告(docs/sudoers-audit-report.md)，覆盖100%autonomous工作流必需命令
# 安全边界说明（诚实版）：动词优先白名单只约束裸 'git <verb>'/'gh <verb>' 形态。
# 【Issue #2635】前缀锚定条目（-c core.hooksPath=/dev/null * / --git-dir=* /
# -R * / api *）在 (ALL) runas 下实际上恢复了接近 #2334 之前的 git/gh 能力：
# 'gh api *' 允许任意 REST 调用（含 -X DELETE），'git -c core.hooksPath=/dev/null *'
# 允许 clean -fd、reset --hard <任意> 及任意内联 -c 配置（含 alias RCE）。
# 前缀是公开常量，仅作命令形态兼容锚点，不是安全边界；真正的收紧由
# 后续 hardened wrapper（openace-git/openace-gh，follow-up issue）承接。
# Issue #2280: GIT_SAFE/GH_SAFE 使用 (ALL) runas 以允许 github_ops 跨用户执行
# Issue #2334: git/gh 从 OPENACE_UTILS 移除，仅通过 GIT_SAFE/GH_SAFE 授权

# git命令白名单（动词优先条目 + #2635 前缀锚定条目）
# 【Issue #2334】使用 (ALL) runas 以支持 github_ops 跨用户操作
# 【Issue #2635】前缀锚定条目：github_ops._run_git 的 sudo 路径在子命令前携带
# git 全局选项（-c core.hooksPath=/dev/null ... 或 --git-dir=... --work-tree=...），
# git 语法要求全局选项必须位于子命令之前，因此命令永不以 'git <subcommand>' 开头，
# 动词优先白名单一条都匹配不上。
# 注意：前缀锚定条目在 (ALL) runas 下近似恢复旧版 'git *' 能力（非更窄）；
# 前缀是公开常量 = 形态兼容锚点，非安全边界；真正的收紧由后续
# hardened wrapper（openace-git）承接（follow-up issue）。
Cmnd_Alias GIT_SAFE = \\
    ${GIT_PATH} -c core.hooksPath=/dev/null *, \\
    ${GIT_PATH} --git-dir=*, \\
    ${GIT_PATH} config --global --add safe.directory *, \\
    ${GIT_PATH} remote get-url origin, \\
    ${GIT_PATH} remote add *, \\
    ${GIT_PATH} checkout *, \\
    ${GIT_PATH} checkout -b *, \\
    ${GIT_PATH} checkout -b * *, \\
    ${GIT_PATH} push *, \\
    ${GIT_PATH} push -u *, \\
    ${GIT_PATH} push origin *, \\
    ${GIT_PATH} push origin --delete *, \\
    ${GIT_PATH} push origin * --force-with-lease, \\
    ${GIT_PATH} fetch *, \\
    ${GIT_PATH} pull *, \\
    ${GIT_PATH} merge *, \\
    ${GIT_PATH} rebase *, \\
    ${GIT_PATH} reset --hard HEAD, \\
    ${GIT_PATH} branch *, \\
    ${GIT_PATH} branch --show-current, \\
    ${GIT_PATH} branch -D *, \\
    ${GIT_PATH} rev-parse *, \\
    ${GIT_PATH} rev-list --count *, \\
    ${GIT_PATH} worktree add *, \\
    ${GIT_PATH} worktree add -b *, \\
    ${GIT_PATH} worktree remove *, \\
    ${GIT_PATH} worktree remove * --force, \\
    ${GIT_PATH} worktree list --porcelain, \\
    ${GIT_PATH} diff *, \\
    ${GIT_PATH} diff --numstat *, \\
    ${GIT_PATH} show *, \\
    ${GIT_PATH} show --format= *, \\
    ${GIT_PATH} show --numstat --format= *, \\
    ${GIT_PATH} status --porcelain, \\
    ${GIT_PATH} status *, \\
    ${GIT_PATH} log *, \\
    ${GIT_PATH} add *, \\
    ${GIT_PATH} add -A, \\
    ${GIT_PATH} commit *, \\
    ${GIT_PATH} commit -m *, \\
    ${GIT_PATH} commit -m * --no-verify, \\
    ${GIT_PATH} init

# gh命令白名单（动词优先条目 + #2635 前缀锚定条目）
# Issue #1855: --admin 仅在 OPENACE_ALLOW_ADMIN_MERGE=1 时启用
# 【Issue #2334】使用 (ALL) runas 以支持 github_ops 跨用户操作
# 【Issue #2635】前缀锚定条目：github_ops._run_gh 的 sudo 路径总是在子命令前插入
# '-R owner/repo'（gh 无 -C，sudo 下靠 -R 定位仓库）；且 gh api 拒绝 -R、以
# 'gh api repos/...' 裸形态运行。
# 注意：'gh api *' 允许任意 REST 调用（含 -X DELETE），'-R *' 下的动词同样
# 不受白名单约束——此两条在 (ALL) runas 下近似恢复旧版 'gh *' 能力（非更窄）；
# 前缀是公开常量 = 形态兼容锚点，非安全边界；真正的收紧由后续
# hardened wrapper（openace-gh）承接（follow-up issue）。
Cmnd_Alias GH_SAFE = \\
    ${GH_PATH} -R *, \\
    ${GH_PATH} api *, \\
    ${GH_PATH} repo create *, \\
    ${GH_PATH} repo create * --private, \\
    ${GH_PATH} repo create * --public, \\
    ${GH_PATH} repo create * --description *, \\
    ${GH_PATH} repo view --json *, \\
    ${GH_PATH} issue create --title * --body *, \\
    ${GH_PATH} issue create --title * --body * --label *, \\
    ${GH_PATH} issue view * --json *, \\
    ${GH_PATH} issue comment * --body *, \\
    ${GH_PATH} issue view * --comments --json *, \\
    ${GH_PATH} issue edit * --title *, \\
    ${GH_PATH} issue edit * --body *, \\
    ${GH_PATH} issue close *, \\
    ${GH_PATH} issue reopen *, \\
    ${GH_PATH} pr create --title * --body * --base *, \\
    ${GH_PATH} pr create --title * --body * --base * --head *, \\
    ${GH_PATH} pr create --title * --body * --base * --head * --draft, \\
    ${GH_PATH} pr view * --json *, \\
    ${GH_PATH} pr comment * --body *, \\
    ${GH_PATH} pr merge *, \\
    ${GH_PATH} pr merge * --merge, \\
    ${GH_PATH} pr merge * --squash, \\
    ${GH_PATH} pr merge * --rebase, \\
    ${GH_PATH} pr merge * --auto, \\
    ${GH_ADMIN_RULE}${GH_PATH} pr view * --json commits, \\
    ${GH_PATH} pr checks * --json *, \\
    ${GH_PATH} pr diff *, \\
    ${GH_PATH} pr list *, \\
    ${GH_PATH} api user, \\
    ${GH_PATH} api repos/*/pulls/*/comments --jq *, \\
    ${GH_PATH} api repos/*/issues/*/comments --jq *

# 【安全加固 Issue #2334】OPENACE_UTILS 收紧
# 移除 git/gh 通配（改用 GIT_SAFE/GH_SAFE）
# 移除 root-runas mkdir（改用 openace-mkdir wrapper）
# 保留低风险只读命令：test, ls, stat, id, find
# find 是只读操作，DAC 已保护敏感目录
Cmnd_Alias OPENACE_UTILS = /usr/bin/test *, /usr/bin/ls *, /usr/bin/stat *, /usr/bin/id *, /usr/bin/find *

# 【Issue #2674】跨用户 mkdir：github_ops.create_verification_worktree_dir 发
# 'sudo -u <account> mkdir -p -- <path>' / 'mkdir -m 700 -- <path>'（裸 mkdir，
# 非 openace-mkdir wrapper——wrapper 仅 (root) runas 且产生 root 属主目录，
# 而 verifier worktree 必须由执行 git 的身份持有）。sudo 按调用方 PATH 解析
# 裸 mkdir，/usr/bin 与 /bin 两种解析路径都必须匹配。
Cmnd_Alias MKDIR_SAFE = /usr/bin/mkdir *, /bin/mkdir *

# ============================================================================
# 用户权限配置
# ============================================================================

# Git/GH rules with (ALL) runas for cross-user operations (Issue #2280)
# These allow github_ops to run git/gh as system_account
${RUN_USER} ALL=(ALL) NOPASSWD: GIT_SAFE
${RUN_USER} ALL=(ALL) NOPASSWD: GH_SAFE
# 【Issue #2674】跨用户 mkdir：github_ops verifier worktree 目录创建
${RUN_USER} ALL=(ALL) NOPASSWD: MKDIR_SAFE

# WebUI launcher - wrapper required (no fallback per Issue #2334)
${WEBUI_RULES}

# Agent CLI - Isolated sandbox only
${WRAPPER_RULE}

# Security wrappers (root runas only - validated internally)
${SECURITY_WRAPPERS_RULES}

# Low-risk utilities (root runas only)
${RUN_USER} ALL=(root) NOPASSWD: OPENACE_UTILS

# ============================================================================
# Preserve environment variables for sudo env_keep passing.
# ============================================================================
# 【安全加固 Issue #2181 + #2334】清理敏感变量
# Agent 进程通过 openace-run-as --isolated 使用 env -i，不继承 env_keep
# env_keep 主要用于 WebUI 启动（sudo -u），需要清理敏感凭据
# 移除：OPENAI_API_KEY, ANTHROPIC_API_KEY, GEMINI_API_KEY, OPENCLAW_TOKEN, GH_TOKEN
# 保留：非敏感变量（proxy_token, GIT_*签名变量, PATH）
Defaults env_keep += \"OPENACE_PROXY_TOKEN OPENACE_PROXY_URL OPENACE_MODEL OPENACE_LOG_DIR PATH\"
Defaults env_keep += \"GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL\"
Defaults env_keep += \"SESSION_TIMEOUT_MS KEEPALIVE_INTERVAL_MS\"
"

# ============================================================================
# Dry run mode: output content and exit
# ============================================================================
if [[ "$DRY_RUN" = true ]]; then
    echo "$SUDOERS_CONTENT"
    exit 0
fi

# ============================================================================
# Atomic install protocol
# ============================================================================

# Write to temp file first
TEMP_FILE=$(mktemp)
trap 'rm -f "$TEMP_FILE"' EXIT

echo "$SUDOERS_CONTENT" > "$TEMP_FILE"
chmod 440 "$TEMP_FILE"

# Validate with visudo
if ! visudo -c -f "$TEMP_FILE" >/dev/null 2>&1; then
    echo "ERROR: sudoers syntax validation failed" >&2
    visudo -c -f "$TEMP_FILE" 2>&1 || true
    exit 3
fi

# Backup existing file if present
BACKUP_FILE=""
if [[ -f "$OUTPUT_FILE" ]]; then
    BACKUP_FILE="${OUTPUT_FILE}.bak.$(date +%s)"
    if ! cp -p "$OUTPUT_FILE" "$BACKUP_FILE" 2>/dev/null; then
        echo "WARNING: Could not backup existing sudoers file" >&2
        BACKUP_FILE=""
    fi
fi

# Atomic rename
if ! mv "$TEMP_FILE" "$OUTPUT_FILE"; then
    echo "ERROR: Failed to write sudoers file" >&2
    # Restore backup if we have one
    if [[ -n "$BACKUP_FILE" ]] && [[ -f "$BACKUP_FILE" ]]; then
        mv "$BACKUP_FILE" "$OUTPUT_FILE"
        echo "Restored previous sudoers from backup" >&2
    fi
    exit 4
fi

# Clear trap since we succeeded
trap - EXIT

# Write audit log entry
log_audit() {
    local msg="$1"
    mkdir -p "$(dirname "$AUDIT_LOG")" 2>/dev/null || true
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $msg" >> "$AUDIT_LOG" 2>/dev/null || true
}

log_audit "[generate-sudoers] Generated $OUTPUT_FILE for user=$RUN_USER"

echo "Generated sudoers file: $OUTPUT_FILE"
if [[ -n "$BACKUP_FILE" ]]; then
    echo "Backup: $BACKUP_FILE"
fi

exit 0
