#!/bin/bash
# generate-sudoers.sh - Unified sudoers generator for Issue #2334
#
# Single source of truth for sudoers configuration used by both Docker and Package.
# All conditionals are resolved BEFORE writing to the sudoers file.
#
# Usage: generate-sudoers.sh --output <file> [--user <user>] [--dry-run]
#
# Exit codes:
#   0 - Success
#   1 - Invalid arguments
#   2 - Required wrapper missing
#   3 - visudo validation failed
#   4 - Write failed

set -euo pipefail

# Default values
OUTPUT_FILE=""
RUN_USER="open-ace"
DRY_RUN=false
INSTALL_DIR=""

# Audit log configuration
AUDIT_LOG="${AUDIT_LOG:-/var/log/openace/sudoers-audit.log}"

usage() {
    echo "Usage: $0 --output <file> [--user <user>] [--install-dir <dir>] [--dry-run]"
    echo ""
    echo "Options:"
    echo "  --output <file>      Output sudoers file path (required)"
    echo "  --user <user>        Service user (default: open-ace)"
    echo "  --install-dir <dir>  Installation directory for path resolution"
    echo "  --dry-run            Show generated content without writing"
    exit 1
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        --user)
            RUN_USER="$2"
            shift 2
            ;;
        --install-dir)
            INSTALL_DIR="$2"
            shift 2
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        -h|--help)
            usage
            ;;
        *)
            echo "Unknown option: $1" >&2
            usage
            ;;
    esac
done

if [[ -z "$OUTPUT_FILE" ]]; then
    echo "ERROR: --output is required" >&2
    usage
fi

# ============================================================================
# Resolve all paths and validate wrappers BEFORE generating content
# ============================================================================

# Resolve git and gh paths
GIT_PATH=$(which git 2>/dev/null || echo "/usr/bin/git")
GH_PATH=$(which gh 2>/dev/null || echo "/usr/bin/gh")

# Resolve WebUI path
WEBUI_PATH=$(which qwen-code-webui 2>/dev/null || echo "/usr/bin/qwen-code-webui")

# Validate required wrappers exist and are executable (skip in dry-run mode)
# In dry-run mode, we're testing the output format, not actual installation
WEBUI_LAUNCH_WRAPPER="/usr/local/bin/openace-webui-launch"
RUN_AS_WRAPPER="/usr/local/bin/openace-run-as"

if [[ "$DRY_RUN" != true ]]; then
    if [[ ! -x "$WEBUI_LAUNCH_WRAPPER" ]]; then
        echo "ERROR: Required wrapper not executable: $WEBUI_LAUNCH_WRAPPER" >&2
        echo "       WebUI launcher wrapper must be installed before generating sudoers" >&2
        exit 2
    fi

    if [[ ! -x "$RUN_AS_WRAPPER" ]]; then
        echo "ERROR: Required wrapper not executable: $RUN_AS_WRAPPER" >&2
        exit 2
    fi
fi

# ============================================================================
# Build sudoers content with all conditionals pre-resolved
# ============================================================================

# Build WebUI launcher rules (fail-closed, no fallback)
WEBUI_RULES="${RUN_USER} ALL=(ALL) NOPASSWD: ${WEBUI_LAUNCH_WRAPPER} * \"${WEBUI_PATH}\" *"

# Build run-as wrapper rules
WRAPPER_RULE="${RUN_USER} ALL=(root) NOPASSWD: ${RUN_AS_WRAPPER} --isolated *"

# Build security wrapper rules
# In dry-run mode, show all expected wrappers for testing
# In production mode, only include wrappers that actually exist
SECURITY_WRAPPERS_RULES=""
for wrapper in openace-chown openace-useradd openace-cat openace-mkdir openace-write-as openace-rm; do
    wrapper_path="/usr/local/bin/${wrapper}"
    if [[ "$DRY_RUN" = true ]] || [[ -x "$wrapper_path" ]]; then
        SECURITY_WRAPPERS_RULES="${SECURITY_WRAPPERS_RULES}
${RUN_USER} ALL=(root) NOPASSWD: ${wrapper_path} *"
    fi
done

# Generate the sudoers content
# Key change for Issue #2334: GIT_SAFE and GH_SAFE use (ALL) runas
# to allow github_ops to run as system_account
SUDOERS_CONTENT="# Open ACE WebUI - Multi-user workspace sudo configuration
# Auto-generated by generate-sudoers.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Issue #2334: Unified generator for Docker and Package paths
#
# Support both open-ace (container user) and openace (workspace user synced from database)

# ============================================================================
# 【安全加固 Issue #2334】精确参数白名单配置
# ============================================================================
# git/gh cross-user command grammar is enforced by openace-git/openace-gh.
# sudoers authorizes only those wrapper binaries; direct git/gh wildcards are not a security boundary.
# Issue #2280: GIT_SAFE/GH_SAFE 使用 (ALL) runas 以允许 github_ops 跨用户执行
# Issue #2334: git/gh 从 OPENACE_UTILS 移除，仅通过 GIT_SAFE/GH_SAFE 授权

# git/gh cross-user operations are validated by root-owned wrappers (#2650).
Cmnd_Alias GIT_SAFE = /usr/local/bin/openace-git *
Cmnd_Alias GH_SAFE = /usr/local/bin/openace-gh *

# 【安全加固 Issue #2334】OPENACE_UTILS 收紧
# 移除 git/gh 通配（改用 GIT_SAFE/GH_SAFE）
# 移除 root-runas mkdir（改用 openace-mkdir wrapper）
# 保留低风险只读命令：test, ls, stat, id, find
# find 是只读操作，DAC 已保护敏感目录
Cmnd_Alias OPENACE_UTILS = /usr/bin/test *, /usr/bin/ls *, /usr/bin/stat *, /usr/bin/id *, /usr/bin/find *

# 【Issue #2674】跨用户 mkdir：github_ops.create_verification_worktree_dir 发
# 'sudo -u <account> mkdir -p -- <path>' / 'mkdir -m 700 -- <path>'（裸 mkdir，
# 非 openace-mkdir wrapper——wrapper 仅 (root) runas 且产生 root 属主目录，
# 而 verifier worktree 必须由执行 git 的身份持有）。sudo 按调用方 PATH 解析
# 裸 mkdir，/usr/bin 与 /bin 两种解析路径都必须匹配。
Cmnd_Alias MKDIR_SAFE = /usr/bin/mkdir *, /bin/mkdir *

# ============================================================================
# 用户权限配置
# ============================================================================

# Git/GH rules with (ALL) runas for cross-user operations (Issue #2280)
# These allow github_ops to run git/gh as system_account
${RUN_USER} ALL=(ALL) NOPASSWD: GIT_SAFE
${RUN_USER} ALL=(ALL) NOPASSWD: GH_SAFE
# 【Issue #2674】跨用户 mkdir：github_ops verifier worktree 目录创建
${RUN_USER} ALL=(ALL) NOPASSWD: MKDIR_SAFE

# WebUI launcher - wrapper required (no fallback per Issue #2334)
${WEBUI_RULES}

# Agent CLI - Isolated sandbox only
${WRAPPER_RULE}

# Security wrappers (root runas only - validated internally)
${SECURITY_WRAPPERS_RULES}

# Low-risk utilities (root runas only)
${RUN_USER} ALL=(root) NOPASSWD: OPENACE_UTILS

# ============================================================================
# Preserve environment variables for sudo env_keep passing.
# ============================================================================
# 【安全加固 Issue #2181 + #2334】清理敏感变量
# Agent 进程通过 openace-run-as --isolated 使用 env -i，不继承 env_keep
# env_keep 主要用于 WebUI 启动（sudo -u），需要清理敏感凭据
# 移除：OPENAI_API_KEY, ANTHROPIC_API_KEY, GEMINI_API_KEY, OPENCLAW_TOKEN, GH_TOKEN
# 保留：非敏感变量（proxy_token, GIT_*签名变量, PATH）
Defaults env_keep += \"OPENACE_PROXY_TOKEN OPENACE_PROXY_URL OPENACE_MODEL OPENACE_LOG_DIR PATH\"
Defaults env_keep += \"GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL\"
Defaults env_keep += \"SESSION_TIMEOUT_MS KEEPALIVE_INTERVAL_MS\"
Defaults secure_path = /usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
"

# ============================================================================
# Dry run mode: output content and exit
# ============================================================================
if [[ "$DRY_RUN" = true ]]; then
    echo "$SUDOERS_CONTENT"
    exit 0
fi

# ============================================================================
# Atomic install protocol
# ============================================================================

# Write to temp file first
TEMP_FILE=$(mktemp)
trap 'rm -f "$TEMP_FILE"' EXIT

echo "$SUDOERS_CONTENT" > "$TEMP_FILE"
chmod 440 "$TEMP_FILE"

# Validate with visudo
if ! visudo -c -f "$TEMP_FILE" >/dev/null 2>&1; then
    echo "ERROR: sudoers syntax validation failed" >&2
    visudo -c -f "$TEMP_FILE" 2>&1 || true
    exit 3
fi

# Backup existing file if present
BACKUP_FILE=""
if [[ -f "$OUTPUT_FILE" ]]; then
    BACKUP_FILE="${OUTPUT_FILE}.bak.$(date +%s)"
    if ! cp -p "$OUTPUT_FILE" "$BACKUP_FILE" 2>/dev/null; then
        echo "WARNING: Could not backup existing sudoers file" >&2
        BACKUP_FILE=""
    fi
fi

# Atomic rename
if ! mv "$TEMP_FILE" "$OUTPUT_FILE"; then
    echo "ERROR: Failed to write sudoers file" >&2
    # Restore backup if we have one
    if [[ -n "$BACKUP_FILE" ]] && [[ -f "$BACKUP_FILE" ]]; then
        mv "$BACKUP_FILE" "$OUTPUT_FILE"
        echo "Restored previous sudoers from backup" >&2
    fi
    exit 4
fi

# Clear trap since we succeeded
trap - EXIT

# Write audit log entry
log_audit() {
    local msg="$1"
    mkdir -p "$(dirname "$AUDIT_LOG")" 2>/dev/null || true
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $msg" >> "$AUDIT_LOG" 2>/dev/null || true
}

log_audit "[generate-sudoers] Generated $OUTPUT_FILE for user=$RUN_USER"

echo "Generated sudoers file: $OUTPUT_FILE"
if [[ -n "$BACKUP_FILE" ]]; then
    echo "Backup: $BACKUP_FILE"
fi

exit 0
