# Open ACE - Backup ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-ace-backup
  namespace: open-ace
  labels:
    app.kubernetes.io/name: open-ace
    app.kubernetes.io/component: backup
