"""Regression guard: the black version must be unified across toolchains.

The CI merge gate runs ``pre-commit run --all-files``, whose ``black`` hook
uses the version pinned in ``.pre-commit-config.yaml``. The autonomous
CI-repair agent and every CI lane install from ``requirements-ci.lock``
(generated from ``requirements-ci.in`` via ``uv pip compile``). When the two
black versions drift apart (issue #2538), the agent's reformat under one
version is undone by the gate's version, so CI-repair never converges.

This test asserts all four declaration points agree on the *same exact*
black version:

* ``.pre-commit-config.yaml``  -> ``rev:``
* ``requirements-ci.in``        -> ``black==X.Y.Z`` (exact pin, not ``>=``)
* ``pyproject.toml``            -> dev/optional-dependency group
* ``requirements-ci.lock``      -> ``black==X.Y.Z`` (what actually installs)

The lock is the load-bearing assertion: it is the file that gets installed,
so a pin that is correct in the gate but wrong/missing in the lock reproduces
the exact drift we are guarding against. If a deliberate bump happens, all
four files must move together and this test is updated as part of that
change.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

try:
    import yaml
except ImportError:  # pragma: no cover - pyyaml is a core dep in CI
    yaml = None  # type: ignore[assignment]

REPO_ROOT = Path(__file__).resolve().parents[2]
PRE_COMMIT_CONFIG = REPO_ROOT / ".pre-commit-config.yaml"
REQUIREMENTS_CI_IN = REPO_ROOT / "requirements-ci.in"
REQUIREMENTS_CI_LOCK = REPO_ROOT / "requirements-ci.lock"
PYPROJECT_TOML = REPO_ROOT / "pyproject.toml"


def _pre_commit_black_version() -> str:
    """Return the black rev pinned in .pre-commit-config.yaml."""
    if yaml is None:
        pytest.skip("PyYAML not installed")
    data = yaml.safe_load(PRE_COMMIT_CONFIG.read_text())
    for repo in data.get("repos", []):
        if str(repo.get("repo", "")).rstrip("/").endswith("psf/black"):
            rev = str(repo.get("rev", "")).strip()
            if rev:
                return rev
    pytest.fail("No psf/black repo found in .pre-commit-config.yaml")


def _requirements_ci_in_black_version() -> str:
    """Return the exact black version pinned in requirements-ci.in.

    An exact ``==X.Y.Z`` pin is required (not an unbounded ``>=``) so the
    generated lock resolves deterministically to the gate version.
    """
    text = REQUIREMENTS_CI_IN.read_text()
    match = re.search(r"^\s*black\s*(==\s*[\d.]+)", text, re.MULTILINE)
    if not match:
        pytest.fail(
            "black is not pinned with an exact '==X.Y.Z' in requirements-ci.in; "
            "an unbounded pin lets the lock drift from the pre-commit gate"
        )
    return match.group(1).replace("==", "").strip()


def _requirements_ci_lock_black_version() -> str:
    """Return the exact black version resolved in requirements-ci.lock."""
    text = REQUIREMENTS_CI_LOCK.read_text()
    match = re.search(r"^black==([\d.]+)", text, re.MULTILINE)
    if not match:
        pytest.fail("black not found in requirements-ci.lock")
    return match.group(1).strip()


def _pyproject_black_version() -> str:
    """Return the exact black version pinned in pyproject.toml dev deps.

    Looks for ``"black==X.Y.Z"`` in the optional-dependencies dev group (a
    formatter must not be an exact runtime pin in [project.dependencies]).
    """
    text = PYPROJECT_TOML.read_text()
    match = re.search(r'["\']black==([\d.]+)["\']', text)
    if not match:
        pytest.fail(
            "black is not pinned with an exact '==X.Y.Z' in pyproject.toml "
            "(expected in the dev optional-dependency group)"
        )
    return match.group(1).strip()


@pytest.mark.regression
def test_black_version_aligned_across_toolchains():
    """All four black declaration points must agree on the same version.

    pre-commit's black (the CI merge gate) and the lock that installs black
    for the autonomous agent and CI lanes are generated from different files.
    A mismatch makes CI-repair reformat under one version and have it undone
    by the gate's version. Align all pins to the same version.
    """
    pre_commit_version = _pre_commit_black_version()
    ci_in_version = _requirements_ci_in_black_version()
    lock_version = _requirements_ci_lock_black_version()
    pyproject_version = _pyproject_black_version()

    assert ci_in_version == pre_commit_version, (
        f"black version drift: .pre-commit-config.yaml pins black "
        f"{pre_commit_version} (the CI merge gate) but requirements-ci.in "
        f"pins black {ci_in_version}. The autonomous agent installs from the "
        f"lock generated by requirements-ci.in, so a mismatch makes CI-repair "
        f"reformat under one version and have it undone by the gate's version. "
        f"Align both pins to the same version."
    )
    assert lock_version == pre_commit_version, (
        f"black version drift: .pre-commit-config.yaml pins black "
        f"{pre_commit_version} but requirements-ci.lock resolved "
        f"black {lock_version}. The lock is what actually gets installed for "
        f"the agent and CI lanes, so it must match the gate. Re-run "
        f"`uv pip compile --universal --python-version 3.10 requirements-ci.in`."
    )
    assert pyproject_version == pre_commit_version, (
        f"black version drift: .pre-commit-config.yaml pins black "
        f"{pre_commit_version} but pyproject.toml pins black "
        f"{pyproject_version}. Keep the dev-deps pin in lockstep with the gate."
    )
