"""Regression guard: black version must be unified across toolchains.

The CI merge gate runs ``pre-commit run --all-files``, whose ``black`` hook
uses the version pinned in ``.pre-commit-config.yaml`` (25.1.0). The
autonomous CI-repair agent and every CI lane install from
``requirements-ci.lock`` (generated from ``requirements-ci.in``). When the two
black versions drift apart (issue #2538), the agent's reformat under one
version is undone by the gate's version, so CI-repair never converges.

This test asserts the two pins declare the same black major.minor.patch so
the drift cannot silently recur. If a deliberate bump happens, both files
must move together and this test is updated as part of that change.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

try:
    import yaml
except ImportError:  # pragma: no cover - pyyaml is a core dep in CI
    yaml = None  # type: ignore[assignment]

REPO_ROOT = Path(__file__).resolve().parents[2]
PRE_COMMIT_CONFIG = REPO_ROOT / ".pre-commit-config.yaml"
REQUIREMENTS_CI_IN = REPO_ROOT / "requirements-ci.in"


def _pre_commit_black_version() -> str:
    """Return the black rev pinned in .pre-commit-config.yaml."""
    if yaml is None:
        pytest.skip("PyYAML not installed")
    data = yaml.safe_load(PRE_COMMIT_CONFIG.read_text())
    for repo in data.get("repos", []):
        if str(repo.get("repo", "")).rstrip("/").endswith("psf/black"):
            rev = str(repo.get("rev", "")).strip()
            if rev:
                return rev
    pytest.fail("No psf/black repo found in .pre-commit-config.yaml")


def _requirements_ci_in_black_version() -> str:
    """Return the exact black version pinned in requirements-ci.in.

    The .in source may use ``==25.1.0`` or ``>=23.0.0,<26.0.0`` style pins.
    We extract the lower-bound / exact version that the lock resolves to.
    For the alignment contract, an exact ``==X.Y.Z`` pin is required so the
    generated lock matches the pre-commit gate deterministically.
    """
    text = REQUIREMENTS_CI_IN.read_text()
    match = re.search(r"^\s*black\s*(==\s*[\d.]+)", text, re.MULTILINE)
    if not match:
        pytest.fail(
            "black is not pinned with an exact '==X.Y.Z' in requirements-ci.in; "
            "an unbounded pin lets the lock drift from the pre-commit gate"
        )
    return match.group(1).replace("==", "").strip()


@pytest.mark.regression
def test_pre_commit_black_matches_requirements_ci_in_pin():
    """The pre-commit gate black and the agent toolchain black must match.

    pre-commit's black (25.1.0) is the merge gate. The lock that installs
    black for the autonomous agent and CI lanes is generated from
    requirements-ci.in, so the .in pin must declare the same version. If this
    test fails, bump BOTH files together as part of an intentional upgrade.
    """
    pre_commit_version = _pre_commit_black_version()
    ci_in_version = _requirements_ci_in_black_version()

    assert ci_in_version == pre_commit_version, (
        f"black version drift: .pre-commit-config.yaml pins black {pre_commit_version} "
        f"(the CI merge gate) but requirements-ci.in pins black {ci_in_version}. "
        f"The autonomous agent installs from the lock generated by requirements-ci.in, "
        f"so a mismatch makes CI-repair reformat under one version and have it undone "
        f"by the gate's version. Align both pins to the same version."
    )
